version: '3.8'

services:
  postgresql:
    image: postgres:17.5-bullseye
    container_name: ecom_postgresql_hybrid
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: ecom_hybrid_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_hybrid_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d ecom_hybrid_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  mongodb:
    image: mongo:6.0
    container_name: ecom_mongodb_hybrid
    ports:
      - "27017:27017"
    command: mongod --bind_ip_all --noauth
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_hybrid_data:
  mongodb_data:
